FROM $IMAGE
RUN $Commands

ARG BRIDGE=synopsys-bridge-linux64.zip
ARG URL=https://sig-repo.synopsys.com/artifactory/bds-integrations-release/com/synopsys/integration/synopsys-bridge/latest
ADD ${URL}/${BRIDGE}

RUN unzip -d /opt/bridge ${BRIDGE}; rm ${BRIDGE}

ENV PATH = ${PATH}:/opt/bridge

CMD ["bash"]
